version: 2

jobs:
  test:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      # - restore_cache:
      #     key: jars-{{ checksum "unit/BasicSample/build.gradle" }}-{{ checksum  "unit/BasicSample/app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew test
      # - save_cache:
      #     key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #     paths:
      #       - ./node_modules
      #       - ./public

  # build:
  #   docker:
  #     - image: docker:17.05.0-ce-git
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - restore_cache:
  #         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  #     - run:
  #         name: Login to dockerhub
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: Docker build
  #         command: docker build -t mbssantos/oplab:$CIRCLE_SHA1 .
  #     - run:
  #         name: Push to dockerhub
  #         command: docker push mbssantos/oplab:$CIRCLE_SHA1
  #
  # lint:
  #   docker:
  #     - image: circleci/node:10
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  #     - run: npm run lint-ci
  #     - run: npm run stylelint-ci
  #
  # test:
  #   docker:
  #     - image: circleci/node:10
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  #     - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
      # - build:
      #     requires:
      #       - dependencies
      # - lint:
      #     requires:
      #       - build
      # - test:
      #     requires:
      #       - build
